Boxplot
edgararuiz-zz/dbplot pull request #28
Opened 2019-10-04 15:20 UTC by edgararuiz

@mkirzon - I split the parts that handle the parts of the calculations that need to be customized.  Would you mind testing this branch before I merge to make sure the changes still work for you? 

To install use:  `remotes::install_github("edgararuiz/dbplot", ref = "boxplot")`

2019-10-04 17:56 UTC, mkirzon commented
Thanks! I'll try to test shortly. This is neat to see and I hadn't considered using methods. Out of curiosity, why do we have a separate method and then a similarly named function for each class? For example, why do we have `calc_boxplot.tbl_spark` and then it calls `calc_boxplot_sparklyr`?

2019-10-04 18:06 UTC, edgararuiz commented
Thank you.  Yes, I separated the method from the functionality so that I can test it without having to simulate the class.  Worked well for MS SQL, but it didn't work as well for `sparklyr`, I'll need to revisit that test

2019-10-04 18:17 UTC, mkirzon commented
That's what I figured - good to know!

On Fri, Oct 4, 2019 at 11:06 AM Edgar Ruiz <notifications@github.com> wrote:

> Thank you. Yes, I separated the method from the functionality so that I
> can test it without having to simulate the class. Worked well for MS SQL,
> but it didn't work as well for sparklyr, I'll need to revisit that test
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/edgararuiz/dbplot/pull/28?email_source=notifications&email_token=ABLHLLDWURGWFQ5TRYI5EUDQM6A3HA5CNFSM4I5RE372YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAMOTPA#issuecomment-538503612>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABLHLLAQO4F5G2IOO3FNKA3QM6A3HANCNFSM4I5RE37Q>
> .
>

2019-10-04 20:08 UTC, mkirzon commented on R/boxplot.R
>    res <- group_by(data, !!x, add = TRUE)
Just realized that it would make `x` an optional argument and to then only do the additive group if `x` was provided.

2019-10-04 20:10 UTC, mkirzon requested changes
I tested it against SQL Server and it worked splendidly! See my one comment about more intuitive argument handling

2019-10-06 14:00 UTC, edgararuiz commented on R/boxplot.R
>    res <- group_by(data, !!x, add = TRUE)
Right, I'd like to think through that a bit more since `x` is the second argument, so you'd have to pass `var` as a named argument

2019-10-06 14:01 UTC, edgararuiz commented
Fixes #23

2019-10-06 14:01 UTC, merged